name: simpletoptagger
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.10
  - pip
  - pandas
  - numpy
  - matplotlib
  - scikit-learn
  - jupyter
  - jupyterlab
  - pytorch
  - torchvision
  - pip:
    - jupyter-server-proxy
    - h5py
    - tables
